#!/usr/bin/env python3
"""Ground truth for the C++ byte-level BPE in `engine/src/ai/bpe_tokenizer.cpp`.

The engine reads `vocab.json` + `merges.txt` itself rather than taking a tokenizer
dependency, so the two have to be diffed against each other. This writes the fixture
`engine/tests/fixtures/florence-tokenizer.json`, which `engine/tests/ai_test.cpp`
reads and compares id for id.

    .venv/bin/python tokenizer_fixture.py
    .venv/bin/python tokenizer_fixture.py --print       # stdout only
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from tokenizers import Tokenizer

from common import MODEL_STORE

# What Florence-2 actually sees: the task token is swapped for a sentence before the
# tokenizer ever runs (florence2.py, TASK_PROMPTS_WITH_INPUT), so every case here is a
# full "Locate ... in the image." prompt plus the edge cases a user can type.
PROMPTS = [
    "Locate the person in the image.",
    "Locate the hat in the image.",
    "Locate the dog in the image.",
    "Locate a red bicycle leaning on a wall in the image.",
    "Locate the woman's hat in the image.",
    "Locate 3 sheep in the image.",
    "Locate the left-hand window in the image.",
    "Locate  the   sky in the image.",
    "Locate the objects with category name in the image.",
    "the cat",
    "",
]

FIXTURE = (
    Path(__file__).resolve().parents[2] / "engine/tests/fixtures/florence-tokenizer.json"
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", action="store_true", help="write to stdout, not the fixture")
    arguments = parser.parse_args()

    model_dir = MODEL_STORE / "florence-2-base"
    tokenizer = Tokenizer.from_file(str(model_dir / "tokenizer.json"))
    payload = {
        "model": "florence-2-base",
        "note": "generated by scripts/models/tokenizer_fixture.py; do not hand-edit",
        "cases": [
            {"text": prompt, "ids": tokenizer.encode(prompt, add_special_tokens=False).ids}
            for prompt in PROMPTS
        ],
    }
    text = json.dumps(payload, indent=2) + "\n"
    if arguments.print:
        print(text, end="")
        return 0
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(text)
    print(f"wrote {FIXTURE} ({len(PROMPTS)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
