// GENERATED from protocol/messages.schema.json by packages/protocol/scripts/generate.ts.
// Do not edit. Change the schema and run `bun run generate`.

export type MethodName =
  | "engine.hello"
  | "ops.describe"
  | "photo.open"
  | "photo.close"
  | "stack.get"
  | "stack.set"
  | "op.add"
  | "op.update"
  | "op.remove"
  | "history.undo"
  | "history.redo"
  | "view.open"
  | "view.close"
  | "view.render"
  | "python.run"
  | "catalog.import"
  | "catalog.list"
  | "catalog.get"
  | "catalog.folders"
  | "catalog.setRating"
  | "catalog.setFlag"
  | "catalog.collections"
  | "catalog.collectionSet"
  | "catalog.thumbnail"
  | "catalog.thumbnails"
  | "catalog.remove"
  | "job.cancel"
  | "merge.hdr"
  | "merge.panorama"
  | "merge.hdrPanorama"
  | "merge.preview"
  | "mask.preview"
  | "mask.detect"
  | "generative.run"
  | "generative.status"
  | "mask.stroke"
  | "export.run"
  | "stack.changed"
  | "engine.log"
  | "catalog.changed"
  | "job.progress"
  | "python.output"
  | "python.finished";
/**
 * Engine → UI messages without an id. Calling one as a method is a -32601 error.
 */
export type NotificationName =
  | "stack.changed"
  | "engine.log"
  | "catalog.changed"
  | "job.progress"
  | "python.output"
  | "python.finished";
/**
 * Stable catalog id (SQLite rowid), so an i64. LTHM binary frames carry it in a u32 slot (protocol/frames.md), which caps thumbnails at 4294967295: catalog.thumbnail and catalog.thumbnails answer -32602 for a larger id instead of sending a frame with a truncated target. Every other method takes the full range.
 */
export type PhotoId = number;
export type ViewId = number;
export type OpId = string;
/**
 * Mirrors Lightroom's Masking panel. AI kinds (subject, sky, background, objects, people, text) rasterise through mask.detect as a job; the rest rasterise inline from their params.
 */
export type MaskComponentKind =
  | "subject"
  | "sky"
  | "background"
  | "objects"
  | "people"
  | "text"
  | "brush"
  | "linear"
  | "radial"
  | "luminance"
  | "color"
  | "depth";
export type JobId = number;
export type Stack = Op[];
/**
 * jpeg is 8-bit with the ICC in APP2; tiff16 and png are 16 bits per channel; avif is 10-bit AV1. The UI builds its format menu from this enum.
 */
export type ExportFormat = "jpeg" | "tiff16" | "png" | "avif";
/**
 * The output profile. The engine converts from its linear working space in the last GPU pass and embeds the matching ICC, generated by lcms2 from the same primaries and curve.
 */
export type ExportColorSpace = "srgb" | "displayP3" | "adobeRGB" | "rec2020" | "proPhoto";
export type PhotoFlag = "none" | "pick" | "reject";
/**
 * One python.run execution. Unique per engine process, so a client can tell its own run's output from another socket's.
 */
export type RunId = number;
/**
 * Notification: the stack of a photo changed by any writer (UI, script, MCP). Carries the new state so the UI never re-fetches.
 */
export type StackChangedParams = StackGetResult & {
  photoId: PhotoId;
  /**
   * `ui` = the receiving client made this change itself; `external` = another socket did; `python`/`mcp` = a script or agent; `history` = undo/redo; `load` = sidecar restore on open.
   */
  source: "ui" | "external" | "python" | "mcp" | "history" | "load";
  /**
   * Who caused the change, one step more specific than `source` and free-form so it can name a tool: `ui`, `external`, `python`, `mcp:<tool>` (e.g. `mcp:run_python`), `history`, `load`. Per socket like `source` is — the writer sees `ui`, the others `external`. A console prints it; nothing branches on it.
   */
  client?: string;
};
/**
 * Lightroom's Deghost Amount. The reference is the middle exposure; a pixel whose radiance differs from it by more than the level's threshold (low 1.0 EV, medium 0.5 EV, high 0.25 EV) drops that frame's contribution.
 */
export type MergeDeghost = "none" | "low" | "medium" | "high";
/**
 * Lightroom's Layout projection. `perspective` composes on a flat canvas; `cylindrical` and `spherical` pre-warp each frame around the focal length read from EXIF before composing.
 */
export type MergeProjection = "spherical" | "cylindrical" | "perspective";
export type MergeKind = "hdr" | "panorama" | "hdrPanorama";

/**
 * JSON-RPC 2.0 methods between the Latent engine and its UI. Each method has <Method>Params and <Method>Result. Phase 0 surface only.
 */
export interface LatentProtocol {
  Envelope?: Envelope;
  RpcError?: RpcError;
  MethodName?: MethodName;
  NotificationName?: NotificationName;
  PhotoId?: PhotoId;
  ViewId?: ViewId;
  OpId?: OpId;
  Op?: Op;
  Mask?: Mask;
  MaskComponentKind?: MaskComponentKind;
  MaskComponent?: MaskComponent;
  MaskPreviewParams?: MaskPreviewParams;
  MaskPreviewResult?: MaskPreviewResult;
  MaskDetectParams?: MaskDetectParams;
  MaskDetectResult?: MaskDetectResult;
  GenerativeRunParams?: GenerativeRunParams;
  GenerativeRunResult?: GenerativeRunResult;
  GenerativeStatusParams?: GenerativeStatusParams;
  GenerativeStatusResult?: GenerativeStatusResult;
  MaskStrokeParams?: MaskStrokeParams;
  MaskStrokeResult?: StackGetResult;
  ExportFormat?: ExportFormat;
  ExportColorSpace?: ExportColorSpace;
  ExportResize?: ExportResize;
  ExportSharpen?: ExportSharpen;
  ExportRunParams?: ExportRunParams;
  ExportRunResult?: ExportRunResult;
  Stack?: Stack;
  OpParamSpec?: OpParamSpec;
  OpParamDisplay?: OpParamDisplay;
  OpDefinition?: OpDefinition;
  Histogram?: Histogram;
  EngineHelloParams?: EngineHelloParams;
  EngineHelloResult?: EngineHelloResult;
  OpsDescribeParams?: OpsDescribeParams;
  OpsDescribeResult?: OpsDescribeResult;
  PhotoOpenParams?: PhotoOpenParams;
  PhotoOpenResult?: PhotoOpenResult;
  PhotoCloseParams?: PhotoCloseParams;
  PhotoCloseResult?: PhotoCloseResult;
  StackGetParams?: StackGetParams;
  StackGetResult?: StackGetResult;
  StackSetParams?: StackSetParams;
  StackSetResult?: StackGetResult;
  OpAddParams?: OpAddParams;
  OpAddResult?: StackGetResult;
  OpUpdateParams?: OpUpdateParams;
  OpUpdateResult?: StackGetResult;
  OpRemoveParams?: OpRemoveParams;
  OpRemoveResult?: StackGetResult;
  HistoryUndoParams?: StackGetParams;
  HistoryUndoResult?: StackGetResult;
  HistoryRedoParams?: StackGetParams;
  HistoryRedoResult?: StackGetResult;
  ViewOpenParams?: ViewOpenParams;
  ViewOpenResult?: ViewOpenResult;
  ViewCloseParams?: ViewCloseParams;
  ViewCloseResult?: ViewCloseResult;
  ViewRenderParams?: ViewRenderParams;
  ViewRenderResult?: ViewRenderResult;
  PythonRunParams?: PythonRunParams;
  PythonRunResult?: PythonRunResult;
  PythonOutputParams?: PythonOutputParams;
  PythonFinishedParams?: PythonFinishedParams;
  StackChangedParams?: StackChangedParams;
  EngineLogParams?: EngineLogParams;
  PhotoFlag?: PhotoFlag;
  CatalogPhoto?: CatalogPhoto;
  CatalogCollection?: CatalogCollection;
  JobId?: JobId;
  RunId?: RunId;
  CatalogImportParams?: CatalogImportParams;
  CatalogImportResult?: CatalogImportResult;
  CatalogListParams?: CatalogListParams;
  CatalogListResult?: CatalogListResult;
  CatalogGetParams?: CatalogGetParams;
  CatalogGetResult?: CatalogPhoto;
  CatalogFoldersParams?: CatalogFoldersParams;
  CatalogFoldersResult?: CatalogFoldersResult;
  CatalogSetRatingParams?: CatalogSetRatingParams;
  CatalogSetRatingResult?: CatalogPhoto;
  CatalogSetFlagParams?: CatalogSetFlagParams;
  CatalogSetFlagResult?: CatalogPhoto;
  CatalogCollectionsParams?: CatalogCollectionsParams;
  CatalogCollectionsResult?: CatalogCollectionsResult;
  CatalogCollectionSetParams?: CatalogCollectionSetParams;
  CatalogCollectionSetResult?: CatalogCollectionsResult;
  CatalogThumbnailParams?: CatalogThumbnailParams;
  CatalogThumbnailResult?: CatalogThumbnailResult;
  CatalogThumbnailsParams?: CatalogThumbnailsParams;
  CatalogThumbnailsResult?: CatalogThumbnailsResult;
  CatalogRemoveParams?: CatalogRemoveParams;
  CatalogRemoveResult?: CatalogRemoveResult;
  JobCancelParams?: JobCancelParams;
  JobCancelResult?: JobCancelResult;
  CatalogChangedParams?: CatalogChangedParams;
  JobProgressParams?: JobProgressParams;
  JobResult?: JobResult;
  MergeDeghost?: MergeDeghost;
  MergeProjection?: MergeProjection;
  MergeKind?: MergeKind;
  MergeHdrParams?: MergeHdrParams;
  MergeHdrResult?: MergeHdrResult;
  MergePanoramaParams?: MergePanoramaParams;
  MergePanoramaResult?: MergePanoramaResult;
  MergeHdrPanoramaParams?: MergeHdrPanoramaParams;
  MergeHdrPanoramaResult?: MergeHdrPanoramaResult;
  MergePreviewParams?: MergePreviewParams;
  MergePreviewResult?: MergePreviewResult;
}
/**
 * JSON-RPC 2.0 envelope. `id` absent on notifications.
 */
export interface Envelope {
  jsonrpc: "2.0";
  id?: number | string;
  method?: MethodName;
  params?: {
    [k: string]: unknown | undefined;
  };
  result?: unknown;
  error?: RpcError;
}
export interface RpcError {
  code: number;
  message: string;
  data?: unknown;
}
/**
 * One entry of the op-stack. `op` names a definition from ops.describe; `params` validates against that definition's schema.
 */
export interface Op {
  id: OpId;
  op: string;
  params: {
    [k: string]: unknown | undefined;
  };
  mask?: Mask;
  /**
   * Layer opacity 0–100; absent means 100. The op's output is mixed into its input by opacity × mask.
   */
  opacity?: number;
  enabled: boolean;
  /**
   * Generative ops only (PROMPT.md 3.5): the cached raster this op produced, as a PNG path relative to `<photo>.latent.d/` — `generative/<opId>.png`. Absent until a generative.run has landed; the op renders as if it were not there until then. A client round-trips it untouched.
   */
  result?: string;
  /**
   * Generative ops only: sha256 over the ops that produced `result`'s input, the op's mask and its params. Engine-owned; a client round-trips it untouched.
   */
  inputHash?: string;
  /**
   * Generative ops only: `[x0, y0, x1, y1]` of `result` inside the content rect, normalised 0..1 — where the crop was cut from and where the composite puts it back. Engine-owned.
   *
   * @minItems 4
   * @maxItems 4
   */
  resultRect?: [number, number, number, number];
  /**
   * Engine-derived, never stored: `inputHash` no longer matches the stack, so `result` was made from other pixels. A stale op still renders its last result — re-running is always explicit (generative.run).
   */
  stale?: boolean;
}
/**
 * A per-op mask: components combined top-down with add / subtract / intersect (PROMPT.md §3.7). Rasters live in the engine; the UI only ever sees them as LMSK frames from mask.preview. An op with a mask renders as mix(in, op(in), mask × opacity).
 */
export interface Mask {
  components: MaskComponent[];
  /**
   * Which space every component's coordinates are normalised over. `image` is 0..1 across the uncropped, unrotated, untransformed photo — the size photo.open reports, camera orientation already applied — and is what the engine writes and renders: a mask painted on the subject stays on it when crop, straighten, rotate, flip or the Transform sliders move afterwards. `content` is the pre-2026-09-16 convention, 0..1 over the content rect of whatever view drew it; only a sidecar written before this change holds one, and the engine converts it through the stack's own geometry the first time it opens the photo and writes `image` back. Absent means `image`: a client that does not send the field is a client that never applied geometry either. The two spaces coincide for an uncropped photo.
   */
  space?: "image" | "content";
}
/**
 * The engine always emits `id` and `mode`. It tolerates a write without them (generates an id, defaults mode to `add`) as leniency for scripts, not as contract: a UI sends both.
 */
export interface MaskComponent {
  id: OpId;
  kind: MaskComponentKind;
  mode: "add" | "subtract" | "intersect";
  /**
   * Absent = false.
   */
  invert?: boolean;
  /**
   * Edge softness 0–100; absent = 0 for AI/luminance/color, the tool's own default for brush/linear/radial.
   */
  feather?: number;
  /**
   * Component strength 0–100; absent = 100.
   */
  opacity?: number;
  /**
   * Kind-specific, all coordinates normalised 0..1 over the image (Mask.space), never over the cropped view: use ViewRenderResult.imageTransform to put one on a canvas. A brush's `size` is a diameter as a fraction of the image's long edge, in the same space. linear: {start:[x,y], end:[x,y]}. radial: {center:[x,y], radius:[rx,ry], angle}. luminance: {range:[lo,hi], smoothness}. color: {samples:[[r,g,b]], range, smoothness}. brush: {size, flow} plus engine-owned `strokeData` (the stroke list — it lives in the op so one undo drops one stroke) and `strokes` (the path it is mirrored to); strokes are appended with mask.stroke, never sent whole. objects: {box:[x0,y0,x1,y1]} or {points:[[x,y]]}. people: {person, parts?}. text: {prompt}. AI kinds carry {model, sourceHash, raster: <cached PNG path relative to <photo>.latent.d/>} once rasterised and `error` after a failed detect. A client round-trips strokeData, strokes, raster and error untouched.
   */
  params?: {
    [k: string]: unknown | undefined;
  };
  /**
   * Engine-owned. ready = raster cached for these params; pending = mask.detect job running; stale = params or source changed since the raster (not auto re-run); failed = last job failed.
   */
  state?: "ready" | "pending" | "stale" | "failed";
  jobId?: JobId;
}
export interface MaskPreviewParams {
  photoId: PhotoId;
  opId: OpId;
  /**
   * One component's raster instead of the combined mask.
   */
  componentId?: string;
  /**
   * Size the raster like this view's proxy so the overlay maps 1:1 onto the frame. Absent = the photo's proxy size.
   */
  viewId?: number;
}
/**
 * Sent after exactly one LMSK frame on the calling socket (protocol/frames.md). `width`/`height` are the view's full proxy size, letterbox included; `coverage` is measured over the image rect inside it. A component in `pending` or `failed` state contributes nothing to the combined raster; asking for its own raster is a -32602 error.
 */
export interface MaskPreviewResult {
  width: number;
  height: number;
  /**
   * [x, y, width, height] of the image inside the proxy, in proxy pixels. Where the raster's photo pixels are; zoomed in it runs outside the frame, so x and y can be negative and the rect can be wider than the frame.
   *
   * @minItems 4
   * @maxItems 4
   */
  contentRect?: [number, number, number, number];
  /**
   * Same matrix as ViewRenderResult.imageTransform, for the raster's own pixel grid: image-normalised → raster pixel.
   *
   * @minItems 9
   * @maxItems 9
   */
  imageTransform?: [number, number, number, number, number, number, number, number, number];
  /**
   * Fraction 0..1 of pixels above 50 %, so a client can tell an empty mask from a failed one.
   */
  coverage?: number;
}
/**
 * Starts (or re-runs) the AI rasterisation of one component. The component goes `pending` immediately (stack.changed), the job ticks job.progress with kind "mask", and on completion the component is `ready` or `failed` (stack.changed again). Non-AI kinds are a -32602 error.
 */
export interface MaskDetectParams {
  photoId: PhotoId;
  opId: OpId;
  componentId: OpId;
  /**
   * Overrides the component's params for this run: {box}, {points}, {prompt}. Stored back into the component on success.
   */
  hint?: {
    [k: string]: unknown | undefined;
  };
}
export interface MaskDetectResult {
  jobId: JobId;
}
/**
 * Runs one generative op (PROMPT.md 3.5). The engine renders the ops below it, crops the op's mask bounding box plus padding to at most 1536 px on the long edge, hands the crop and the mask to the backend, and stores the result as `Op.result`. Ticks job.progress with kind "generative" and publishes stack.changed when it lands. Nothing else ever starts a run: an op whose `stale` is true keeps rendering its last result until this is called again. An op that is not generative, or has no mask, is a -32602 error.
 */
export interface GenerativeRunParams {
  photoId: PhotoId;
  opId: OpId;
}
export interface GenerativeRunResult {
  jobId: JobId;
}
export interface GenerativeStatusParams {}
/**
 * Whether a generative run can succeed right now, and why not. A UI shows `message`/`hint` instead of letting a run fail silently.
 */
export interface GenerativeStatusResult {
  /**
   * What the ops' `backend: "auto"` resolves to on this daemon.
   */
  backend: string;
  backends?: string[];
  /**
   * LATENT_GENERATIVE_STUB=1: runs answer with a blurred stand-in and never touch ComfyUI.
   */
  stub?: boolean;
  ready: boolean;
  message?: string;
  hint?: string;
  comfy: {
    installed: boolean;
    path?: string;
    serverRunning: boolean;
    workspace?: string;
    error?: string;
    message?: string;
  };
  /**
   * Weight files under the ComfyUI workspace's models/{checkpoints,unet,diffusion_models}. What an op's `model` param may name.
   */
  models?: string[];
  workflows: {
    name: string;
    task: "fill" | "remove";
    label?: string;
    /**
     * Every weight file the graph loads is installed.
     */
    ready: boolean;
    requires?: string[];
  }[];
}
/**
 * Appends a stroke segment to a brush component. The engine owns the stroke list and its raster; the UI never uploads pixels. Only brush components accept strokes (-32602 otherwise).
 */
export interface MaskStrokeParams {
  photoId: PhotoId;
  opId: OpId;
  componentId: OpId;
  /**
   * @minItems 1
   */
  points: [
    [number, number] | [number, number, number],
    ...([number, number] | [number, number, number])[]
  ];
  /**
   * Absent = paint.
   */
  erase?: boolean;
  /**
   * Brush diameter as a fraction of the image's long edge; absent = the component's params.size.
   */
  size?: number;
  flow?: number;
  /**
   * True for every segment of one pointer-down; the first non-transient call (pointer-up) snapshots, so a stroke undoes as one step.
   */
  transient?: boolean;
}
export interface StackGetResult {
  stack: Stack;
  revision: number;
  canUndo: boolean;
  canRedo: boolean;
  histogram?: Histogram;
}
export interface Histogram {
  bins: number;
  r: number[];
  g: number[];
  b: number[];
  clippedShadowsPct: number;
  clippedHighlightsPct: number;
}
/**
 * Absent or empty means native resolution: the crop rect at sensor pixels. width and height together are a box the image is fitted inside, aspect kept. Resampling happens on the GPU in linear light, before the output curve.
 */
export interface ExportResize {
  /**
   * Fit the long side to this many pixels. Wins over width/height.
   */
  longEdge?: number;
  width?: number;
  height?: number;
  /**
   * Metadata only — JFIF density, PNG pHYs, TIFF resolution. It never changes the pixel count.
   */
  dpi?: number;
}
/**
 * Output sharpening, Lightroom's three targets. It is the last pass before the colour transform and is not part of the develop; absent means none.
 */
export interface ExportSharpen {
  target: "screen" | "matte" | "glossy";
  /**
   * Absent = standard.
   */
  amount?: "low" | "standard" | "high";
}
/**
 * Starts a batch export and returns immediately. Progress arrives as job.progress kind `export`, whose `message` is the file currently being written; job.cancel stops it between photos.
 */
export interface ExportRunParams {
  /**
   * Catalog rows. A photo that is not open is decoded for the export and dropped again; an open one keeps its texture.
   *
   * @minItems 1
   */
  photoIds: [PhotoId, ...PhotoId[]];
  format: ExportFormat;
  /**
   * JPEG and AVIF only; ignored by the lossless formats. Default 90.
   */
  quality?: number;
  colorSpace: ExportColorSpace;
  resize?: ExportResize;
  sharpen?: ExportSharpen;
  /**
   * Created if it does not exist.
   */
  outputDir: string;
  /**
   * `{name}` is the source file's stem, `{index}` its 1-based position in this run, `{ext}` the format's extension. Default `{name}`. Path separators are stripped — a template names a file, never a path — and the extension is forced.
   */
  fileNameTemplate?: string;
}
export interface ExportRunResult {
  jobId: JobId;
  /**
   * How many files the job will write — photoIds.length, so a bar can size itself before the first progress arrives.
   */
  total: number;
}
/**
 * One slider/control of an op, in Lightroom terms.
 */
export interface OpParamSpec {
  name: string;
  label?: string;
  type: "number" | "integer" | "boolean" | "enum" | "curve" | "string";
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  default: unknown;
  values?: string[];
  display?: OpParamDisplay;
}
/**
 * How a generated panel should draw this param. Advisory: a UI that ignores it still renders a correct control from `type`, `min`, `max` and `step`.
 */
export interface OpParamDisplay {
  /**
   * `slider` is the default control. `kelvin` is a white-balance temperature slider, `curve` a tone-curve editor, `hsl` an eight-band colour mixer, `toggle` a checkbox, `text` a free-text field — a generative prompt or a model name, drawn by a hand-built panel.
   */
  kind: "slider" | "kelvin" | "curve" | "hsl" | "toggle" | "text";
  /**
   * Gradient to paint under the track, the way Lightroom tints Temp blue→yellow and Tint green→magenta.
   */
  tint?: "temperature" | "tint" | "hue" | "saturation";
}
export interface OpDefinition {
  name: string;
  /**
   * Lightroom's Edit-panel section this op is drawn in. The display name of `panel`, and the heading a generated panel groups under.
   */
  section?: "Light" | "Color" | "Effects" | "Detail" | "Optics" | "Geometry" | "Generative";
  /**
   * Position inside `section`, ascending, following Lightroom's slider order. Ops without one sort last, then by name.
   */
  order?: number;
  /**
   * The op accepts `mask` and `opacity` (every develop op). Geometry ops and generative ops that own their region are not maskable; absent = false.
   */
  maskable?: boolean;
  panel: "light" | "color" | "effects" | "detail" | "optics" | "geometry" | "generative";
  label: string;
  params: OpParamSpec[];
}
export interface EngineHelloParams {
  client?: string;
}
export interface EngineHelloResult {
  engineVersion: string;
  protocolVersion: number;
  /**
   * Absolute path of the SQLite catalog this daemon opened. A UI shows which catalog it is on; a test asserts it is the throwaway one and not ~/.local/share/latent/catalog.db.
   */
  catalogPath: string;
  /**
   * Streamable-HTTP endpoint of the engine's MCP server, e.g. http://127.0.0.1:7801/mcp. Absent when the daemon was started with --no-mcp or the SDK failed to load.
   */
  mcpUrl?: string;
  gpu: {
    adapter: string;
    maxTextureDimension2D: number;
    shaderF16: boolean;
  };
}
export interface OpsDescribeParams {}
export interface OpsDescribeResult {
  ops: OpDefinition[];
}
export interface PhotoOpenParams {
  path: string;
}
/**
 * Opening a file catalogs it, so `catalog` carries the row and a client never has to follow photo.open with catalog.get. It is absent only when the engine opened a file it did not catalog.
 */
export interface PhotoOpenResult {
  photoId: PhotoId;
  width: number;
  height: number;
  camera: string;
  /**
   * SHA-256 hex of the raw file, as stored in the sidecar.
   */
  hash: string;
  /**
   * True when an existing .latent sidecar was read and its stack restored.
   */
  sidecarLoaded: boolean;
  catalog?: CatalogPhoto;
}
/**
 * One catalog row. `photoId` is the stable id used everywhere else.
 */
export interface CatalogPhoto {
  photoId: PhotoId;
  path: string;
  /**
   * Absolute directory containing the file.
   */
  folder: string;
  filename: string;
  width: number;
  height: number;
  camera: string;
  lens?: string;
  /**
   * ISO 8601 from EXIF; absent when unknown.
   */
  capturedAt?: string;
  /**
   * ISO 8601.
   */
  importedAt: string;
  /**
   * ISO 8601 of the last non-transient stack change; absent when never edited.
   */
  editedAt?: string;
  rating: number;
  flag: PhotoFlag;
  hasSidecar: boolean;
  /**
   * SHA-256 hex of the raw file, the same value photo.open returns. Present once the engine has hashed the file — an import registers a row before hashing it, so a freshly imported row can lack it until it is opened.
   */
  hash?: string;
  iso?: number;
  /**
   * e.g. "1/250"
   */
  shutter?: string;
  aperture?: number;
  focalLength?: number;
}
export interface PhotoCloseParams {
  photoId: PhotoId;
}
export interface PhotoCloseResult {}
export interface StackGetParams {
  photoId: PhotoId;
}
export interface StackSetParams {
  photoId: PhotoId;
  stack: Stack;
}
export interface OpAddParams {
  photoId: PhotoId;
  op: string;
  /**
   * Omitted keys take the registry defaults; omitted entirely adds the op at defaults.
   */
  params?: {
    [k: string]: unknown | undefined;
  };
  /**
   * Insert position; end of stack when omitted.
   */
  index?: number;
  /**
   * True when the add is the first tick of a slider drag: no history snapshot, no sidecar write, so the whole drag undoes as one step. The first non-transient update after it snapshots.
   */
  transient?: boolean;
  mask?: Mask;
  /**
   * Layer opacity 0–100; absent means 100.
   */
  opacity?: number;
}
export interface OpUpdateParams {
  photoId: PhotoId;
  opId: OpId;
  /**
   * Partial; merged into the op's params.
   */
  params: {
    [k: string]: unknown | undefined;
  };
  enabled?: boolean;
  /**
   * True while a slider is being dragged: no history snapshot, no sidecar write. The first non-transient update after a drag snapshots.
   */
  transient?: boolean;
  /**
   * Full replacement, never a merge: a mask is an ordered list and merging two by index is not something a caller can reason about. `null` clears it.
   */
  mask?: Mask | null;
  /**
   * Layer opacity 0–100; absent leaves it unchanged.
   */
  opacity?: number;
}
export interface OpRemoveParams {
  photoId: PhotoId;
  opId: OpId;
}
/**
 * A view is one canvas showing one photo at one proxy size. Frames for it arrive as LFRM binary frames tagged with viewId.
 */
export interface ViewOpenParams {
  photoId: PhotoId;
  width: number;
  height: number;
}
export interface ViewOpenResult {
  viewId: ViewId;
}
export interface ViewCloseParams {
  viewId: ViewId;
}
export interface ViewCloseResult {}
/**
 * Ask for a frame of the view's current state. Resizing happens here too.
 */
export interface ViewRenderParams {
  viewId: ViewId;
  width?: number;
  height?: number;
  /**
   * How much of the geometry stage this frame applies. `stack` is the whole stack, the default. `full` renders the uncropped image: the crop op's rect and its straighten angle are bypassed so the crop tool can show what is being cropped away, while rotate, flip and Transform still apply because they move the whole image.
   */
  geometry?: "stack" | "full";
  /**
   * Zoom and pan. Sticky per view: send it when it changes, leave it out otherwise and the view stays where it was. It is not edit state — nothing about it reaches the stack or the sidecar.
   */
  viewport?: {
    /**
     * 1 is fit-to-view, the behaviour of every render before this field existed; 2 is twice that. A client computes 1:1 as imageWidth / (contentRect width at scale 1).
     */
    scale: number;
    /**
     * The image-normalised point the view is centred on. Sending neither centre, or a scale of 1, means fit: the image is centred the way it always was. The engine clamps the pan so a zoomed view never shows a bar it could fill with photo, and echoes what it used in the result.
     */
    centerX?: number;
    centerY?: number;
  };
}
export interface ViewRenderResult {
  seq: number;
  /**
   * Stack revision the frame was rendered from — the same counter as StackGetResult.revision. A client that coalesced slider drags compares it with the revision of the last stack.changed it saw to know whether the frame it is holding is the newest state or one render behind.
   */
  revision: number;
  /**
   * Size of the frame that was sent, so a client that dropped it still knows the view size.
   */
  width: number;
  height: number;
  /**
   * [x, y, width, height] of the image inside the proxy, in proxy pixels. Zoomed in it is larger than the frame and x/y go negative, so read it as signed numbers and not as a letterbox.
   *
   * @minItems 4
   * @maxItems 4
   */
  contentRect?: [number, number, number, number];
  /**
   * image-normalised → view pixel: a row-major 3×3 applied to (x, y, 1) with a homogeneous divide, so [m0 m1 m2 m3 m4 m5 m6 m7 m8] means px = (m0·x + m1·y + m2)/w, py = (m3·x + m4·y + m5)/w, w = m6·x + m7·y + m8. Projective and not affine, because the Transform sliders' keystone is. It carries crop, straighten, rotate, flip, Transform and the viewport's zoom and pan, so it converts a pointer to a mask coordinate (through its inverse) and a mask coordinate to a canvas pixel. Lens distortion is deliberately not in it: the radial term has no closed-form inverse, so the matrix is exact wherever lens_correction.distortion is 0, which is its default, and off by that term otherwise. Optional and additive: a client without it falls back to contentRect, which is the same thing whenever nothing is cropped.
   *
   * @minItems 9
   * @maxItems 9
   */
  imageTransform?: [number, number, number, number, number, number, number, number, number];
  /**
   * The viewport this frame was rendered with, after clamping. Echoed so a client that asked for an out-of-range zoom or a pan past the edge shows what it got rather than what it wanted.
   */
  viewport?: {
    scale?: number;
    centerX?: number;
    centerY?: number;
    fit?: boolean;
  };
  renderMs: number;
  readbackMs: number;
}
export interface PythonRunParams {
  code: string;
  /**
   * Stable catalog id (SQLite rowid), so an i64. LTHM binary frames carry it in a u32 slot (protocol/frames.md), which caps thumbnails at 4294967295: catalog.thumbnail and catalog.thumbnails answer -32602 for a larger id instead of sending a frame with a truncated target. Every other method takes the full range.
   */
  photoId?: number;
  /**
   * Wall-clock budget for the script. On expiry the engine interrupts it with KeyboardInterrupt and answers with an error result (`ok: false`, the traceback in `stderr`), never by dropping the call. Default 30000.
   */
  timeoutMs?: number;
}
export interface PythonRunResult {
  ok: boolean;
  /**
   * Wall-clock time the script took, measured around the interpreter call. The same number the run's python.finished carries. Optional only so a client written against an older engine still typechecks; latentd and the mock always send it.
   */
  durationMs?: number;
  stdout: string;
  stderr: string;
  /**
   * repr() of the script's last expression, if any.
   */
  value?: string;
  /**
   * Set when the engine streamed the run's output as python.output notifications. `stdout`/`stderr` still carry the complete streams, so a client that showed the live output replaces it with these when the call returns.
   */
  runId?: number;
}
/**
 * Notification: output a still-running script has produced. Sent to the socket that issued python.run, before that call's result. Long scripts stream; a short one may answer with the result alone.
 */
export interface PythonOutputParams {
  runId: RunId;
  stream: "stdout" | "stderr";
  /**
   * The chunk as written, newlines included. Never re-sent, never trimmed.
   */
  text: string;
}
/**
 * Notification: a run ended. Sent to the socket that issued python.run, after that run's last python.output and before the RPC result, so a console can close the output stream without waiting for the result to arrive.
 */
export interface PythonFinishedParams {
  runId: RunId;
  /**
   * Wall-clock time the script took. Matches the run's PythonRunResult.durationMs.
   */
  durationMs: number;
  /**
   * False when the script raised or ran out of its timeoutMs budget; the traceback is in the result's stderr, not here.
   */
  ok: boolean;
}
export interface EngineLogParams {
  level: "debug" | "info" | "warn" | "error";
  message: string;
  /**
   * Stable catalog id (SQLite rowid), so an i64. LTHM binary frames carry it in a u32 slot (protocol/frames.md), which caps thumbnails at 4294967295: catalog.thumbnail and catalog.thumbnails answer -32602 for a larger id instead of sending a frame with a truncated target. Every other method takes the full range.
   */
  photoId?: number;
}
export interface CatalogCollection {
  collectionId: number;
  name: string;
  count: number;
}
/**
 * Registers files (or every raw in the given directories) in the catalog and queues thumbnails. Returns immediately; progress arrives as job.progress notifications.
 */
export interface CatalogImportParams {
  /**
   * @minItems 1
   */
  paths: [string, ...string[]];
  /**
   * Descend into subdirectories. Default true; only directories in `paths` are affected.
   */
  recursive?: boolean;
}
export interface CatalogImportResult {
  jobId: JobId;
  /**
   * The thumbnail job the import queues behind itself, reserved up front so a client can follow both from the one result. Its job.progress carries parentJobId = jobId. It always reports, even when the import found nothing or was cancelled — then with total 0. Absent from an engine that does not queue thumbnails.
   */
  thumbnailJobId?: number;
}
/**
 * Catalog rows, filtered and sorted. Every property narrows the result; combining them is an AND. Rows with equal sort keys are ordered by filename ascending, then by photoId ascending, so paging is stable and the same list never reshuffles between calls.
 */
export interface CatalogListParams {
  /**
   * Exact folder match; omit for every photo.
   */
  folder?: string;
  /**
   * Exactly these rows, in the list's sort order. Ids that are not in the catalog are left out rather than erroring. Useful for refreshing a selection without re-listing a page.
   */
  photoIds?: PhotoId[];
  /**
   * Case-insensitive substring match over filename and camera. Empty string matches everything.
   */
  query?: string;
  collectionId?: number;
  flag?: PhotoFlag;
  minRating?: number;
  sort?: "capturedAt" | "importedAt" | "filename" | "rating" | "editedAt";
  descending?: boolean;
  limit?: number;
  offset?: number;
}
export interface CatalogListResult {
  photos: CatalogPhoto[];
  /**
   * Matches before limit/offset.
   */
  total: number;
}
export interface CatalogGetParams {
  photoId: PhotoId;
}
export interface CatalogFoldersParams {}
export interface CatalogFoldersResult {
  folders: {
    path: string;
    count: number;
  }[];
}
export interface CatalogSetRatingParams {
  photoId: PhotoId;
  rating: number;
}
export interface CatalogSetFlagParams {
  photoId: PhotoId;
  flag: PhotoFlag;
}
export interface CatalogCollectionsParams {}
export interface CatalogCollectionsResult {
  collections: CatalogCollection[];
}
/**
 * Create (name without collectionId), rename (both), add/remove members, or delete a collection.
 */
export interface CatalogCollectionSetParams {
  collectionId?: number;
  name?: string;
  add?: PhotoId[];
  remove?: PhotoId[];
  delete?: boolean;
}
/**
 * Sends an LTHM binary frame (JPEG, target = photoId) before the result. Cached on disk by the engine; generated from the embedded preview when the raw has one, else from a fast half-size decode. A photoId above 4294967295 does not fit the frame's u32 target and is refused with -32602.
 */
export interface CatalogThumbnailParams {
  photoId: PhotoId;
  /**
   * Long edge in px. Default 256.
   */
  size?: number;
}
export interface CatalogThumbnailResult {
  photoId: PhotoId;
  width: number;
  height: number;
}
/**
 * Batch form of catalog.thumbnail: one LTHM binary frame per photo that has one, all sent before the result. A filmstrip asks for the page it is about to draw in one call instead of one call per cell. An id above 4294967295 does not fit the frame's u32 target: the whole call is refused with -32602 rather than listed in `missing`, because it is a malformed request and not a photo that failed to render.
 */
export interface CatalogThumbnailsParams {
  photoIds: PhotoId[];
  /**
   * Long edge in px, the same for every photo in the batch. Default 256.
   */
  size?: number;
}
/**
 * Sent after the frames. A photo that produced no thumbnail — unknown id, unreadable file, decode failure — is listed in `missing` and has no frame; the call itself does not fail.
 */
export interface CatalogThumbnailsResult {
  /**
   * photoIds after de-duplication.
   */
  requested: number;
  /**
   * Frames sent before this result.
   */
  sent: number;
  missing: PhotoId[];
}
/**
 * Removes catalog rows: the database entries, their thumbnails and their collection memberships. Files on disk and their .latent sidecars are never touched — re-importing the same path brings the photo back (with a new photoId). Ids that are not in the catalog are ignored.
 */
export interface CatalogRemoveParams {
  photoIds: PhotoId[];
}
export interface CatalogRemoveResult {
  /**
   * Rows actually deleted.
   */
  removed: number;
}
/**
 * Asks a running job to stop at its next safe point. Work already done stands: a cancelled import keeps the photos it registered.
 */
export interface JobCancelParams {
  jobId: JobId;
}
export interface JobCancelResult {
  /**
   * True when a running job was asked to stop; false when the job is unknown or already finished. The job's last job.progress then has `finished: true` and `state: "cancelled"`.
   */
  cancelled: boolean;
}
/**
 * Notification: catalog rows changed. Clients re-list what they show.
 */
export interface CatalogChangedParams {
  photoIds: PhotoId[];
  reason: "import" | "rating" | "flag" | "collection" | "edit" | "remove";
}
/**
 * Notification for long-running engine work (import, thumbnails, later export).
 */
export interface JobProgressParams {
  jobId: JobId;
  /**
   * The job that queued this one — set on the thumbnail job an import spawns, absent on a job nobody spawned. A progress UI nests the child under its parent instead of showing two unrelated bars.
   */
  parentJobId?: number;
  kind: "import" | "thumbnails" | "export" | "mask" | "merge" | "generative";
  done: number;
  total: number;
  finished: boolean;
  /**
   * How the job stands. `running` while `finished` is false; one of the other three on the last notification. Absent means `running` until finished, then `done` — so a client written before this field keeps working.
   */
  state?: "running" | "done" | "cancelled" | "error";
  message?: string;
  error?: string;
  result?: JobResult;
}
/**
 * What the job produced, on its last job.progress only — absent while it runs, and absent from a job whose output is the catalog itself (import, thumbnails). Every field is optional: a merge answers `photoId` and `path`, a merge preview answers `previewUrl` and `previewPath` and no photoId.
 */
export interface JobResult {
  /**
   * Stable catalog id (SQLite rowid), so an i64. LTHM binary frames carry it in a u32 slot (protocol/frames.md), which caps thumbnails at 4294967295: catalog.thumbnail and catalog.thumbnails answer -32602 for a larger id instead of sending a frame with a truncated target. Every other method takes the full range.
   */
  photoId?: number;
  /**
   * The file the job wrote.
   */
  path?: string;
  /**
   * http://127.0.0.1:<engine port>/preview/<name>.png — the engine serves the file it just wrote over its own listener, so a renderer can put it in an <img> without a file:// read.
   */
  previewUrl?: string;
  /**
   * The same preview on disk.
   */
  previewPath?: string;
  width?: number;
  height?: number;
  durationMs?: number;
}
/**
 * Merges 2..7 exposure-bracketed photos into one linear 16-bit TIFF, registers it in the catalog and answers its photoId on the job's last job.progress. Tone is the user's job: no auto settings are applied.
 */
export interface MergeHdrParams {
  /**
   * 2 to 7 exposures of one scene, in any order. Fewer or more is a -32602.
   */
  photoIds: PhotoId[];
  /**
   * Lightroom's Deghost Amount. The reference is the middle exposure; a pixel whose radiance differs from it by more than the level's threshold (low 1.0 EV, medium 0.5 EV, high 0.25 EV) drops that frame's contribution.
   */
  deghost?: "none" | "low" | "medium" | "high";
  autoAlign?: boolean;
  /**
   * Absolute path of the TIFF to write. Default: `<first source without extension>-HDR.tif` next to the sources.
   */
  outputPath?: string;
}
export interface MergeHdrResult {
  jobId: JobId;
}
/**
 * Stitches 2..12 overlapping photos into one linear 16-bit TIFF and registers it in the catalog.
 */
export interface MergePanoramaParams {
  /**
   * 2 to 12 overlapping frames, in shooting order. Fewer or more is a -32602; the cap is memory, not the algorithm.
   */
  photoIds: PhotoId[];
  /**
   * Lightroom's Layout projection. `perspective` composes on a flat canvas; `cylindrical` and `spherical` pre-warp each frame around the focal length read from EXIF before composing.
   */
  projection?: "spherical" | "cylindrical" | "perspective";
  /**
   * Warps the mosaic toward the crop rectangle instead of throwing the edges away. 0 = no warp, 100 = the valid content is stretched to fill the rectangle.
   */
  boundaryWarp?: number;
  autoCrop?: boolean;
  outputPath?: string;
}
export interface MergePanoramaResult {
  jobId: JobId;
}
/**
 * Detects the bracket groups by their exposure pattern, merges each to HDR, then stitches the results. Every group must hold the same number of frames and the same EV offsets.
 */
export interface MergeHdrPanoramaParams {
  /**
   * Every frame of every bracket, in shooting order. 4 to 48; the groups are found from the exposure pattern, not from the order alone.
   */
  photoIds: PhotoId[];
  /**
   * Lightroom's Deghost Amount. The reference is the middle exposure; a pixel whose radiance differs from it by more than the level's threshold (low 1.0 EV, medium 0.5 EV, high 0.25 EV) drops that frame's contribution.
   */
  deghost?: "none" | "low" | "medium" | "high";
  autoAlign?: boolean;
  /**
   * Lightroom's Layout projection. `perspective` composes on a flat canvas; `cylindrical` and `spherical` pre-warp each frame around the focal length read from EXIF before composing.
   */
  projection?: "spherical" | "cylindrical" | "perspective";
  boundaryWarp?: number;
  autoCrop?: boolean;
  outputPath?: string;
}
export interface MergeHdrPanoramaResult {
  jobId: JobId;
}
/**
 * The same merge at preview size, from the raws' embedded JPEGs instead of a full decode — seconds instead of minutes. Writes a PNG and names it in the job's last job.progress `result`; nothing is written to the catalog.
 */
export interface MergePreviewParams {
  kind: MergeKind;
  /**
   * The same ids the full merge would get.
   */
  photoIds: PhotoId[];
  /**
   * Lightroom's Deghost Amount. The reference is the middle exposure; a pixel whose radiance differs from it by more than the level's threshold (low 1.0 EV, medium 0.5 EV, high 0.25 EV) drops that frame's contribution.
   */
  deghost?: "none" | "low" | "medium" | "high";
  autoAlign?: boolean;
  /**
   * Lightroom's Layout projection. `perspective` composes on a flat canvas; `cylindrical` and `spherical` pre-warp each frame around the focal length read from EXIF before composing.
   */
  projection?: "spherical" | "cylindrical" | "perspective";
  boundaryWarp?: number;
  autoCrop?: boolean;
  longEdge?: number;
}
export interface MergePreviewResult {
  jobId: JobId;
}
